language: perl
perl: "5.18"
sudo: false
notifications:
  email: false
addons:
  apt:
    packages:
      - libreadline-dev
      - libncurses5-dev
      - libpcre3-dev
      - libssl-dev
      - build-essential
env:
  global:
    - CASSANDRA=2.1.12
    - LUAROCKS=2.3.0
    - OPENRESTY=1.9.7.3
    - CASSANDRA_LOAD=100
    - OPENRESTY_DIR=$HOME/openresty-$OPENRESTY
  matrix:
    - LUA: lua5.1
    - LUA: lua5.2
    - LUA: lua5.3
    - LUA: luajit-2.0
    - LUA: luajit-2.1
    - LUA: luajit-2.1
      OPENRESTY_TESTS: "yes"
before_install:
  - source .ci/setenv_lua.sh
  - source .ci/setenv_openresty.sh
  - bash .ci/setup_ccm.sh
  - luarocks install luasec
  - luarocks install busted
  - luarocks install luacheck
  - luarocks install luacov-coveralls
install:
  - make install
script: .ci/run_tests.sh
cache:
  cpan: true
  apt: true
  pip: true
  directories:
    - $OPENRESTY_DIR
    - $HOME/.ccm/repository/
