language: java
jdk:
  - oraclejdk8
sudo: false
notifications:
  email: false
addons:
  apt:
    packages:
      - libreadline-dev
      - libncurses5-dev
      - libpcre3-dev
      - libssl-dev
      - build-essential
env:
  global:
    - OPENRESTY=1.9.15.1
    - OPENRESTY_DIR=$HOME/openresty
    - PERL_DIR=$HOME/perl5
    - LUA_DIR=$HOME/lua
  matrix:
    - LUA="lua 5.1"
    - LUA="lua 5.2"
    - LUA="luajit 2.0"
    - LUA="luajit 2.1"
    - OPENRESTY_TESTS=true
      LUA="luajit 2.1"
    - OPENRESTY_TESTS=true
      LUA="luajit 2.1"
      CASSANDRA=2.2.7
    - OPENRESTY_TESTS=true
      LUA="luajit 2.1"
      CASSANDRA=2.1.15
before_install:
  - source .ci/setup_env.sh
install:
  - make install
script: .ci/run_tests.sh
cache:
  cpan: true
  apt: true
  pip: true
  directories:
    - $PERL_DIR
    - $OPENRESTY_DIR
    - $HOME/.ccm/repository/
