language: perl
perl: "5.18"
sudo: false
notifications:
  email: false
addons:
  apt:
    packages:
      - libreadline-dev
      - libncurses5-dev
      - libpcre3-dev
      - libssl-dev
      - build-essential
env:
  global:
    - CASSANDRA_VERSION=2.1.12
    - LUAROCKS_VERSION=2.3.0
    - OPENRESTY_VERSION=1.9.7.1
    - LUA_DIR=$HOME/lua
    - OPENRESTY_DIR=$HOME/openresty
    - "CASSANDRA_HOSTS=127.0.0.1,127.0.0.2,127.0.0.3"
    - CASSANDRA_LOAD=100
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit-2.0
    - LUA=luajit-2.1
    - OPENRESTY_TESTS: "yes"
      LUA: luajit-2.1
before_install:
  - source .ci/setenv_lua.sh
  - source .ci/setenv_openresty.sh
  - bash .ci/setup_cassandra.sh
install:
  - make dev
script: .ci/run_tests.sh
cache:
  cpan: true
  apt: true
  pip: true
  directories:
    - $OPENRESTY_DIR
    - $HOME/.ccm/repository/
